server.port: 8089

spring.data.cassandra:
  contact-points: localhost
  port: 9042
  keyspace-name: store
  local-datacenter: datacenter1
  username: root
  password: root

params:
  wishlist-limit: 20